import os, random
from render_pil import render_video
from uploader import upload_video
from tts import synthesize_tts

# ---- Settings from secrets / env ----
TOPIC = os.getenv("VIDEO_TOPIC", "football; Lamine Yamal, Lionel Messi, Cristiano Ronaldo")
VOICE_LANG = os.getenv("VOICE_LANG", "en")
BRAND = os.getenv("BRAND_NAME", "QuickShorts")
PRIVACY = os.getenv("YT_UPLOAD_PRIVACY", "public")
N_VIDEOS = 3  # how many shorts per run

# ---- Helpers ----
def slugify(s: str) -> str:
    return "".join(ch if ch.isalnum() else "-" for ch in s)[:50].strip("-")

def build_description(title: str, brand: str, script: str):
    credit = (
        "Background b-roll via Pexels API. "
        "Video auto-generated by " + brand + "."
    )
    hashtags = "#shorts #football #soccer #messi #ronaldo #lamineyamal"
    return script + "\n\n" + credit + "\n\n" + hashtags

# Simple football-focused script generator (no extra API needed)
def make_football_script() -> str:
    hooks = [
        "Quick football fact:",
        "30 seconds of football:",
        "A tiny football story:",
        "Football bite of the day:",
    ]
    facts = [
        "Lamine Yamal is Barcelona’s teenage sensation rewriting age records.",
        "Lionel Messi holds the most Ballon d’Or awards in history.",
        "Cristiano Ronaldo is the men’s all-time top international scorer.",
        "El Clásico shaped careers for both Messi and Ronaldo.",
        "Young talents change games—watch Yamal’s confidence on the wing.",
        "Top tip: first touch + quick decision beats raw speed.",
        "Finishing: open your body and hit across the keeper.",
        "Off-the-ball runs create goals you never touch.",
        "Low-driven crosses are deadly in the box.",
        "Small-sided practice builds elite close control."
    ]
    hook = random.choice(hooks)
    chosen = random.sample(facts, 3)
    outro = "More football in the next short."
    return "\n".join([hook] + chosen + [outro])

def main():
    for i in range(N_VIDEOS):
        # 1) Write a short football script
        script = make_football_script()

        # 2) Create voice-over mp3 from the script
        voice_path = synthesize_tts(script, lang=VOICE_LANG, outfile=f"/tmp/voice-{i}.mp3")

        # 3) Render vertical video with football b-roll + captions + voice
        title = f"Football bite #{i+1} — {TOPIC.split(';')[0].strip().title()}"
        filename = f"short-{slugify(title)}.mp4"
        path = os.path.join("/tmp", filename)
        render_video(script, brand_name=BRAND, outfile=path, topic=TOPIC, voice_path=voice_path)

        # 4) Upload to YouTube
        desc = build_description(title, BRAND, script)
        upload_video(path, title, desc, privacy_status=PRIVACY)

if __name__ == "__main__":
    main()
