name: Publish QuickShorts

on:
  workflow_dispatch: {}
  # If you want it to run on every commit, uncomment the next 2 lines.
  # push:
  #   branches: [main]
  schedule:
    - cron: "0 7,11,15 * * *"   # 07:00, 11:00, 15:00 UTC

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-dejavu-core

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run autoposter
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BRAND_NAME: ${{ secrets.BRAND_NAME }}
          YT_UPLOAD_PRIVACY: ${{ secrets.YT_UPLOAD_PRIVACY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          VIDEO_TOPIC: ${{ secrets.VIDEO_TOPIC }}
          VOICE_LANG: en
        run: |
          python -u src/main.py

      - name: Upload rendered videos (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: renders
          path: /tmp/*.mp4
          if-no-files-found: warn
